fragment BlogParts on Blog {
  __typename
  title
  description
  pubDatetime
  modDatetime
  author
  ogImage
  tags
  featured
  draft
  canonicalURL
  hideEditPost
  timezone
  noindex
  body
}

fragment SettingsParts on Settings {
  __typename
  nav {
    __typename
    title
    href
  }
  socials {
    __typename
    name
    href
    icon
  }
}
