[build]
  command = "gatsby build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
    package = "netlify-plugin-checklinks"

    [plugins.inputs] 
    # You can mark some check as skipped, which will block checklinks
    # from ever attempting to execute them.
    # skipPatterns is an array of strings you can match against failing reports
    skipPatterns = ["https://www.google-analytics.com"]
